In [14]:
# Lab 4 Multi-variable linear regression
from functools import partial as bind
import numpy as np
import tensorflow as tf
assert(tf.__version__.find('2') == 0)
tf.random.set_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

# placeholders for a tensor that will be always fed.
W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

# Hypothesis
hypothesis = lambda X: tf.matmul(X, W) + b

# Simplified cost/loss function
@tf.function
def cost(X, Y):
    return tf.reduce_mean(tf.square(hypothesis(X) - Y))

# Minimize
optimizer = tf.optimizers.SGD(learning_rate=1e-5)

# Launch the graph in a session.

for step in range(2001):
    optimizer.minimize(bind(cost, x_data, y_data), [W, b])
    cost_val = cost(x_data, y_data)
    hy_val = hypothesis(x_data)
    if step == 0 or step == 10 or step == 1990 or step == 2000:
        tf.print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# train output
'''
0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619772 ]
 ...
 [31.36112  ]
 [24.986364 ]]
10 Cost: 95.976326 
Prediction:
 [[157.11063 ]
 [183.99283 ]
 ...
 [167.48862 ]
 [193.25117 ]]
 1990 Cost: 24.863274 
Prediction:
 [[154.4393  ]
 [185.5584  ]
 ...
 [158.27443 ]
 [192.79778 ]]
2000 Cost: 24.722485 
Prediction:
 [[154.42894 ]
 [185.5586  ]
 ...
 [158.24257 ]
 [192.79166 ]]
'''

# Ask my score
prediction = hypothesis(tf.Variable([[100, 70, 101]], dtype=tf.float32))
tf.print("Your score will be ", prediction)

prediction = hypothesis(tf.Variable([[60, 70, 110], [90, 100, 80]], dtype=tf.float32))
tf.print("Other scores will be ", prediction)

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]

'''


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
0 Cost:  2278.57495 
Prediction:
 [[109.386681]
 [132.589]
 [130.285645]
 ...
 [116.086456]
 [113.276413]
 [137.912918]]
10 Cost:  27.966507 
Prediction:
 [[153.673981]
 [185.829239]
 [182.737671]
 ...
 [163.908463]
 [157.905914]
 [193.083969]]
1990 Cost:  11.5017128 
Prediction:
 [[152.846146]
 [185.

'\nYour score will be  [[ 181.73277283]]\nOther scores will be  [[ 145.86265564]\n [ 187.23129272]]\n\n'