In [9]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
assert(tf.__version__.find('2') == 0)
tf.random.set_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.Variable(x1_data)
x2 = tf.Variable(x2_data)
x3 = tf.Variable(x3_data)
Y = tf.Variable(y_data)

w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')

hypothesis = lambda: x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
@tf.function
def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.optimizers.SGD(learning_rate=1e-5)

# Launch the graph in a session.

for step in range(2001):
    optimizer.minimize(cost, [w1, w2, w3, b])
    cost_val = cost()
    hy_val = hypothesis()
    if step == 0 or step == 10 or step == 1990 or step == 2000:
        tf.print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  19614.8
Prediction:
 [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]
10 Cost:  14.0682
Prediction:
 [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]

 ...

1990 Cost:  4.9197
Prediction:
 [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]
2000 Cost:  4.89449
Prediction:
 [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]
'''


0 Cost:  10843.3506 
Prediction:
 [52.3568916 78.3032532 68.9596405 76.370575 62.863102]
10 Cost:  21.0462303 
Prediction:
 [144.40155 188.900513 177.950485 195.056656 147.214432]
1990 Cost:  7.36382055 
Prediction:
 [147.408417 187.370529 179.122284 195.98381 145.05719]
2000 Cost:  7.32565308 
Prediction:
 [147.418823 187.363419 179.125519 195.985931 145.048019]


'\n0 Cost:  19614.8\nPrediction:\n [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]\n10 Cost:  14.0682\nPrediction:\n [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]\n\n ...\n\n1990 Cost:  4.9197\nPrediction:\n [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]\n2000 Cost:  4.89449\nPrediction:\n [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]\n'