In [3]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
assert(tf.__version__.find('2') == 0)
tf.random.set_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.Variable(x_data)
Y = tf.Variable(y_data)

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

# Hypothesis
hypothesis = lambda: tf.matmul(X, W) + b

# Simplified cost/loss function
@tf.function
def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

# Minimize
optimizer = tf.optimizers.SGD(learning_rate=1e-5)

# Launch the graph in a session.

for step in range(2001):
    optimizer.minimize(cost, [W, b])
    cost_val = cost()
    hy_val = hypothesis()
    if step == 0 or step == 10 or step == 1990 or step == 2000:
        tf.print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  7105.46
Prediction:
 [[ 80.82241058]
 [ 92.26364136]
 [ 93.70250702]
 [ 98.09217834]
 [ 72.51759338]]
10 Cost:  5.89726
Prediction:
 [[ 155.35159302]
 [ 181.85691833]
 [ 181.97254944]
 [ 194.21760559]
 [ 140.85707092]]

...

1990 Cost:  3.18588
Prediction:
 [[ 154.36352539]
 [ 182.94833374]
 [ 181.85189819]
 [ 194.35585022]
 [ 142.03240967]]
2000 Cost:  3.1781
Prediction:
 [[ 154.35881042]
 [ 182.95147705]
 [ 181.85035706]
 [ 194.35533142]
 [ 142.036026  ]]

'''


0 Cost:  2043.50073 
Prediction:
 [[112.164352]
 [135.927292]
 [133.575439]
 [144.348099]
 [104.5923]]
10 Cost:  0.495432943 
Prediction:
 [[152.146835]
 [183.987061]
 [180.927567]
 [195.913651]
 [141.250519]]
1990 Cost:  0.304008543 
Prediction:
 [[151.960083]
 [184.343475]
 [180.975952]
 [196.007706]
 [141.632736]]
2000 Cost:  0.303522021 
Prediction:
 [[151.958893]
 [184.344284]
 [180.975586]
 [196.007492]
 [141.633759]]


'\n0 Cost:  7105.46\nPrediction:\n [[ 80.82241058]\n [ 92.26364136]\n [ 93.70250702]\n [ 98.09217834]\n [ 72.51759338]]\n10 Cost:  5.89726\nPrediction:\n [[ 155.35159302]\n [ 181.85691833]\n [ 181.97254944]\n [ 194.21760559]\n [ 140.85707092]]\n\n...\n\n1990 Cost:  3.18588\nPrediction:\n [[ 154.36352539]\n [ 182.94833374]\n [ 181.85189819]\n [ 194.35585022]\n [ 142.03240967]]\n2000 Cost:  3.1781\nPrediction:\n [[ 154.35881042]\n [ 182.95147705]\n [ 181.85035706]\n [ 194.35533142]\n [ 142.036026  ]]\n\n'