In [2]:
from functools import partial as bind
import numpy as np
import tensorflow as tf
assert(tf.__version__.find('2') == 0)
#tf.random.set_seed(777)  # for reproducibility


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = tf.Variable(xy[:, 0:-1], dtype=tf.float32)
y_data = tf.Variable(xy[:, [-1]], dtype=tf.float32)

W = tf.Variable(tf.random.normal([4, 1]), name='weight', dtype=tf.float32)
b = tf.Variable(tf.random.normal([1]), name='bias', dtype=tf.float32)

# Hypothesis
hypothesis = lambda X: tf.matmul(X, W) + b

# Simplified cost/loss function
@tf.function
def cost(X, Y):
    return tf.reduce_mean(tf.square(hypothesis(X) - Y))

# Minimize
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-5)

for step in range(101):
    cost_val = cost(x_data, y_data)
    hy_val = hypothesis(x_data)

    optimizer.minimize(bind(cost, x_data, y_data), var_list=[W, b])

    if step % 10 == 0:
        tf.print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost: 0.15230925 
Prediction:
 [[ 1.6346191 ]
 [ 0.06613699]
 [ 0.3500818 ]
 [ 0.6707252 ]
 [ 0.61130744]
 [ 0.61464405]
 [ 0.23171967]
 [-0.1372836 ]]
1 Cost: 0.15230872 
Prediction:
 [[ 1.634618  ]
 [ 0.06613836]
 [ 0.35008252]
 [ 0.670725  ]
 [ 0.6113076 ]
 [ 0.6146443 ]
 [ 0.23172   ]
 [-0.13728246]]
...
99 Cost: 0.1522546 
Prediction:
 [[ 1.6345041 ]
 [ 0.06627947]
 [ 0.35014683]
 [ 0.670706  ]
 [ 0.6113161 ]
 [ 0.61466044]
 [ 0.23175153]
 [-0.13716647]]
100 Cost: 0.15225402 
Prediction:
 [[ 1.6345029 ]
 [ 0.06628093]
 [ 0.35014752]
 [ 0.67070574]
 [ 0.61131614]
 [ 0.6146606 ]
 [ 0.23175186]
 [-0.13716528]]
'''


[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  0.569470167 
Prediction:
 [[1.07653391]
 [0.121477008]
 [0.681939483]
 ...
 [1.07457757]
 [1.36766899]
 [1.10140014]]
10 Cost:  0.569374204 
Prediction:
 [[1.0763936]
 [0.121335983]
 [0.681811571]
 ...
 [1.07445765]
 [1.36756659]
 [1.10129881]]
20 Cost:  0.569278419 
Prediction:
 [[1.07625341]
 [0.121195197]
 [0.681683779]
 ...
 [1.07433808]
 [1.36746454]
 [1.1011976]]
30 Cost:  0.569183469 
Prediction:
 [[1.07611418]
 [0.121055484]
 [0.681557178]
 ...
 [1.07421935]
 [1.36736333]
 [1.10109735]]
40 Cost:  0.569088578 
Pre

'\n0 Cost: 0.15230925 \nPrediction:\n [[ 1.6346191 ]\n [ 0.06613699]\n [ 0.3500818 ]\n [ 0.6707252 ]\n [ 0.61130744]\n [ 0.61464405]\n [ 0.23171967]\n [-0.1372836 ]]\n1 Cost: 0.15230872 \nPrediction:\n [[ 1.634618  ]\n [ 0.06613836]\n [ 0.35008252]\n [ 0.670725  ]\n [ 0.6113076 ]\n [ 0.6146443 ]\n [ 0.23172   ]\n [-0.13728246]]\n...\n99 Cost: 0.1522546 \nPrediction:\n [[ 1.6345041 ]\n [ 0.06627947]\n [ 0.35014683]\n [ 0.670706  ]\n [ 0.6113161 ]\n [ 0.61466044]\n [ 0.23175153]\n [-0.13716647]]\n100 Cost: 0.15225402 \nPrediction:\n [[ 1.6345029 ]\n [ 0.06628093]\n [ 0.35014752]\n [ 0.67070574]\n [ 0.61131614]\n [ 0.6146606 ]\n [ 0.23175186]\n [-0.13716528]]\n'