In [6]:
# Lab 6 Softmax Classifier
from functools import partial as bind
import tensorflow as tf
assert(tf.__version__.find('2') == 0)

tf.random.set_seed(777)  # for reproducibility

x_data = tf.Variable([[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]], dtype=tf.float32)
y_data = tf.Variable([[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]], dtype=tf.float32)

nb_classes = 3

W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = lambda X: tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
@tf.function
def cost(X, Y):
    return tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis(X)), axis=1))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

# Launch graph
for step in range(20001):
    # Minimize
    optimizer.minimize(bind(cost, x_data, y_data), var_list=[W, b])

    if step % 2000 == 0:
        # evaluate training accuracy
        tf.print("Step: ", step, "cost: ", bind(cost, x_data, y_data)())

print('--------------')
# Testing & One-hot encoding
a = hypothesis(tf.Variable([[1, 11, 7, 9]], dtype=tf.float32))
tf.print(a, tf.argmax(a, 1))

print('--------------')
b = hypothesis(tf.Variable([[1, 3, 4, 3]], dtype=tf.float32))
tf.print(b, tf.argmax(b, 1))

print('--------------')
c = hypothesis(tf.Variable([[1, 1, 0, 1]], dtype=tf.float32))
tf.print(c, tf.argmax(c, 1))

print('--------------')
all = hypothesis(tf.Variable([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]], dtype=tf.float32))
tf.print(all, tf.argmax(all, 1))

'''
0 6.926112
200 0.6005015
400 0.47295815
600 0.37342924
800 0.28018373
1000 0.23280522
1200 0.21065344
1400 0.19229904
1600 0.17682323
1800 0.16359556
2000 0.15216158
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]
-------------
[[0.9311919  0.06290216 0.00590591]] [0]
-------------
[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]
 [9.3119192e-01 6.2902197e-02 5.9059085e-03]
 [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
'''


Step:  0 cost:  5.68203449
Step:  2000 cost:  0.454490781
Step:  4000 cost:  0.373116344
Step:  6000 cost:  0.32182318
Step:  8000 cost:  0.283468723
Step:  10000 cost:  0.253114849
Step:  12000 cost:  0.228399932
Step:  14000 cost:  0.207887754
Step:  16000 cost:  0.190606862
Step:  18000 cost:  0.175865769
Step:  20000 cost:  0.163155675
--------------
[[0.023961924 0.976028323 9.76851788e-06]] [1]
--------------
[[0.713546872 0.257215947 0.0292372461]] [0]
--------------
[[0.000263624388 0.172967941 0.826768398]] [2]
--------------
[[0.440473229 0.559526742 9.97446836e-09]
 [0.988881 0.0111168195 2.25072e-06]
 [0.000263624388 0.172967941 0.826768398]] [1 0 2]


'\n0 6.926112\n200 0.6005015\n400 0.47295815\n600 0.37342924\n800 0.28018373\n1000 0.23280522\n1200 0.21065344\n1400 0.19229904\n1600 0.17682323\n1800 0.16359556\n2000 0.15216158\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]\n-------------\n[[0.9311919  0.06290216 0.00590591]] [0]\n-------------\n[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]\n [9.3119192e-01 6.2902197e-02 5.9059085e-03]\n [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]\n'